### ISSUE TITLE
Very well summed up

### ISSUE THREAD

**Issue by stringzc** [NiuTrans/Introduction-to-Transformers#1]
Why not the whole Chinese readme

**Comment by Lucky-259** [comment]
> Why not the whole Chinese readme

谢谢对我们的关注和建议。我们也计划写一个中文版的内容，近期就会更新。

**Comment by xiaotong** [comment]
> Why not the whole Chinese readme

Thank you very much for your comment. We are certainly interested in creating a Chinese version of this project and are planning to release it soon.
